version: '3'
services:
    yulo-mysql:
        container_name: yulo-mysql
        image: mysql:8.0.30
        env_file:
            - ./env/mysql.env
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/conf:/etc/mysql/conf.d
        ports:
            - "3306:3306"
        healthcheck:
            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
            interval: 5s
            timeout: 10s
            retries: 10

    yulo-redis:
        container_name: yulo-redis
        image: redis
        build:
            context: ./redis
        ports:
            - "6379:6379"
        volumes:
            - ./redis/conf/redis.conf:/home/yulo/redis/redis.conf
            - ./redis/data:/data
        command: redis-server /home/yulo/redis/redis.conf


